apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      
    automated:
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.0

    # https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
    helm:
      valuesObject:
        fullnameOverride: cert-manager
        installCRDs: true
        # resources:
        #   requests:
        #     cpu: 75m
        #     memory: 150Mi
        #   limits:
        #     cpu: 75m
        #     memory: 150Mi
        podDisruptionBudget:
          enabled: true

        # serviceAccount:
        #   annotations:
        #     eks.amazonaws.com/role-arn: arn:aws:iam::{$ACCOUNTID}:policy/route53-cert-manager

        securityContext:
          fsGroup: 1001

        prometheus:
          servicemonitor:
            enabled: false # true
            labels:
              prometheus.io/scrap-with: kube-prometheus-stack

        extraArgs:
          - --logging-format=json
        webhook:
          extraArgs:
            - --logging-format=json
        cainjector:
          extraArgs:
            - --logging-format=json


  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager

