#  Veeam Kasten - Deploy Kasten instances to connect to Primary Multi-Cluster Manager
#  https://docs.kasten.io/latest/multicluster/index.html
#
#
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kasten-io-appset-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster # Remote clusters only
  template:
    metadata:
      name: 'kasten-io-resources-{{name}}'
    spec:
      project: default 
      source:
        repoURL: https://github.com/fullaware/argocd-kasten.git
        targetRevision: HEAD
        path: 'resources/kasten-io-resources'
      destination:
        server: '{{server}}'
        namespace: kasten-io
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: argocd
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s